name: deploy-shinyapps-demo
on:
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:


jobs:
  deploy-shiny:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Push to shinyapps
          run: |
            rsconnect add --account pevolution-ahmed --name pevolution-ahmed --token ${{ secrets.SHINYAPPS_TOKEN }} --secret ${{ secrets.SHINYAPPS_SECRET }}
            rsconnect deploy shiny . --app-id 9675650 --name pevolution-ahmed --title my-app11
