name: deploy-shinyapps-demo
on:
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:


jobs:
  deploy-shiny:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3
          
        # - name: Install dependencies
        #   run: pip install -r requirements.txt
        
        - name: see secrets
          run: echo "${{secrets.SHINYAPPS_SECRET}}"